packages:
  - .

onlyBuiltDependencies:
  - '@smithery/cli'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - bufferutil
  - esbuild
  - sharp
  - unrs-resolver
overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@modelcontextprotocol/sdk@<1.26.0': '>=1.26.0'
  ajv@<6.14.0: '>=6.14.0'
  axios@<1.13.5: '>=1.13.5'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  brace-expansion@<1.1.13: '>=1.1.13'
  cross-spawn@<6.0.6: '>=6.0.6'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  got@<11.8.5: '>=11.8.5'
  http-cache-semantics@<4.1.1: '>=4.1.1'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  minimatch@<3.1.4: '>=3.1.4'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
  path-to-regexp@>=8.0.0 <8.4.0: '>=8.4.0'
  qs@<6.14.2: '>=6.14.2'
  semver-regex@<3.1.4: '>=3.1.4'
  svgo@>=3.0.0 <3.3.3: '>=3.3.3'
