#!/usr/bin/env node

import { execSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";

const DEFAULT_OUTPUT_PATH = ".github/data-refresh-pr-body.md";
const MAX_NAMES_PER_SECTION = 12;

interface PokemonDataEntry {
  id: number;
  name: string;
}

interface FilePokemonDelta {
  filePath: string;
  added: number[];
  removed: number[];
}

function runGitCommand(command: string): string {
  try {
    return execSync(command, {
      cwd: process.cwd(),
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    }).trim();
  } catch (error) {
    const message = error instanceof Error ? error.message : "unknown error";
    throw new Error(`Failed to execute git command '${command}': ${message}`);
  }
}

function readJsonWithContext<T>(jsonText: string, source: string): T {
  try {
    return JSON.parse(jsonText) as T;
  } catch (error) {
    const message = error instanceof Error ? error.message : "unknown error";
    throw new Error(`Failed to parse JSON from ${source}: ${message}`);
  }
}

function collectPokemonIds(node: unknown, target: Set<number>): void {
  if (Array.isArray(node)) {
    for (const child of node) {
      collectPokemonIds(child, target);
    }
    return;
  }

  if (node && typeof node === "object") {
    for (const [key, value] of Object.entries(node)) {
      if (key === "pokemonIds" && Array.isArray(value)) {
        for (const pokemonId of value) {
          if (typeof pokemonId === "number" && Number.isInteger(pokemonId)) {
            target.add(pokemonId);
          }
        }
      } else {
        collectPokemonIds(value, target);
      }
    }
  }
}

function sortedNumeric(set: Set<number>): number[] {
  return Array.from(set).sort((a, b) => a - b);
}

function formatPokemonId(pokemonId: number): string {
  return String(pokemonId).padStart(3, "0");
}

function describePokemon(
  pokemonId: number,
  pokemonNameMap: Map<number, string>,
): string {
  const pokemonName = pokemonNameMap.get(pokemonId) ?? "Unknown";
  return `#${formatPokemonId(pokemonId)} ${pokemonName}`;
}

function formatPokemonList(
  pokemonIds: number[],
  pokemonNameMap: Map<number, string>,
): string {
  if (pokemonIds.length === 0) {
    return "none";
  }

  const displayIds = pokemonIds.slice(0, MAX_NAMES_PER_SECTION);
  const names = displayIds
    .map((pokemonId) => describePokemon(pokemonId, pokemonNameMap))
    .join(", ");

  if (pokemonIds.length > MAX_NAMES_PER_SECTION) {
    return `${names}, and ${pokemonIds.length - MAX_NAMES_PER_SECTION} more`;
  }

  return names;
}

function toSet(values: number[]): Set<number> {
  return new Set(values);
}

function setDifference(left: Set<number>, right: Set<number>): number[] {
  const result = new Set<number>();
  for (const value of left) {
    if (!right.has(value)) {
      result.add(value);
    }
  }

  return sortedNumeric(result);
}

function buildBody(
  changedDataFiles: string[],
  deltas: FilePokemonDelta[],
  pokemonNameMap: Map<number, string>,
): string {
  const addedAcrossFiles = new Set<number>();
  const removedAcrossFiles = new Set<number>();

  for (const delta of deltas) {
    for (const pokemonId of delta.added) {
      addedAcrossFiles.add(pokemonId);
    }
    for (const pokemonId of delta.removed) {
      removedAcrossFiles.add(pokemonId);
    }
  }

  const addedSorted = sortedNumeric(addedAcrossFiles);
  const removedSorted = sortedNumeric(removedAcrossFiles);

  const lines: string[] = [
    "This PR contains automatically updated Pokemon data files.",
    "",
    "## Pokemon Changes",
    `- Added Pokemon (${addedSorted.length}): ${formatPokemonList(addedSorted, pokemonNameMap)}`,
    `- Removed Pokemon (${removedSorted.length}): ${formatPokemonList(removedSorted, pokemonNameMap)}`,
    "",
    "## File Breakdown",
  ];

  const filesWithPokemonChanges = deltas.filter(
    (delta) => delta.added.length > 0 || delta.removed.length > 0,
  );

  if (filesWithPokemonChanges.length === 0) {
    lines.push("- No Pokemon ID additions/removals detected in changed files.");
  } else {
    for (const delta of filesWithPokemonChanges) {
      lines.push(
        `- \`${delta.filePath}\`: +${delta.added.length} / -${delta.removed.length}`,
      );

      if (delta.added.length > 0) {
        lines.push(
          `  - Added: ${formatPokemonList(delta.added, pokemonNameMap)}`,
        );
      }

      if (delta.removed.length > 0) {
        lines.push(
          `  - Removed: ${formatPokemonList(delta.removed, pokemonNameMap)}`,
        );
      }
    }
  }

  lines.push(
    "",
    "## Changed Data Files",
    ...changedDataFiles.map((filePath) => `- \`${filePath}\``),
    "",
    "Generated by: CI data refresh workflow",
    "Triggered by: schedule",
  );

  return `${lines.join("\n")}\n`;
}

async function createPokemonNameMap(): Promise<Map<number, string>> {
  const pokemonDataPath = path.join(
    process.cwd(),
    "data",
    "shared",
    "pokemon-data.json",
  );

  const fileContent = await fs.readFile(pokemonDataPath, "utf8");
  const pokemonData = readJsonWithContext<PokemonDataEntry[]>(
    fileContent,
    pokemonDataPath,
  );

  const pokemonNameMap = new Map<number, string>();
  for (const entry of pokemonData) {
    if (typeof entry.id !== "number" || typeof entry.name !== "string") {
      throw new Error(
        `Invalid Pokemon entry in ${pokemonDataPath}: ${JSON.stringify(entry)}`,
      );
    }

    pokemonNameMap.set(entry.id, entry.name);
  }

  return pokemonNameMap;
}

async function main(): Promise<void> {
  const cliArgs = process.argv.slice(2).filter((arg) => arg !== "--");
  const outputPathArg = cliArgs[0] ?? DEFAULT_OUTPUT_PATH;
  const outputPath = path.resolve(process.cwd(), outputPathArg);

  const changedDataFiles = runGitCommand("git diff --name-only -- data/")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && line.endsWith(".json"))
    .sort((a, b) => a.localeCompare(b));

  const pokemonNameMap = await createPokemonNameMap();

  const deltas: FilePokemonDelta[] = [];

  for (const filePath of changedDataFiles) {
    const nextContent = await fs.readFile(
      path.resolve(process.cwd(), filePath),
      "utf8",
    );
    const nextJson = readJsonWithContext<unknown>(nextContent, filePath);
    const nextIds = new Set<number>();
    collectPokemonIds(nextJson, nextIds);

    let previousIds = new Set<number>();

    try {
      const previousContent = runGitCommand(`git show HEAD:${filePath}`);
      const previousJson = readJsonWithContext<unknown>(
        previousContent,
        `HEAD:${filePath}`,
      );
      previousIds = new Set<number>();
      collectPokemonIds(previousJson, previousIds);
    } catch {
      previousIds = new Set<number>();
    }

    deltas.push({
      filePath,
      added: setDifference(nextIds, previousIds),
      removed: setDifference(previousIds, nextIds),
    });
  }

  const body = buildBody(changedDataFiles, deltas, pokemonNameMap);

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, body, "utf8");

  process.stdout.write(`Generated data PR body: ${outputPath}\n`);
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : "unknown error";
  process.stderr.write(`Failed to generate data PR body: ${message}\n`);
  process.exit(1);
});
